---
# Configuration Grafana
adminPassword: admin123

service:
  type: NodePort
  nodePort: 30300

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:80
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    spring-boot-dashboard:
      json: |
        {
          "dashboard": {
            "title": "Eat Now - Microservices Monitoring",
            "panels": [],
            "schemaVersion": 16,
            "version": 0
          }
        }
