apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - menu-service-deployment.yaml
  - menu-service-service.yaml
  - menu-service-hpa.yaml
  - delivery-service-deployment.yaml
  - delivery-service-service.yaml
  - delivery-service-hpa.yaml
<<<<<<< HEAD
  - order-service-deployment.yaml
  - order-service-service.yaml
  - order-service-hpa.yaml
=======
>>>>>>> origin/achille
  - ingress.yaml

images:
  - name: menu-service
    newName: janovp/menu-service
    newTag: latest
  - name: delivery-service
    newName: janovp/delivery-service
    newTag: latest
<<<<<<< HEAD
  - name: order-service
    newName: janovp/order-service
    newTag: latest
=======
>>>>>>> origin/achille
