apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - menu-service-deployment.yaml
  - menu-service-service.yaml
  - menu-service-hpa.yaml
  - delivery-service-deployment.yaml
  - delivery-service-service.yaml
  - delivery-service-hpa.yaml
  - ingress.yaml

images:
  - name: menu-service
    newName: janovp/menu-service
    newTag: latest
  - name: delivery-service
    newName: janovp/delivery-service
    newTag: latest
