server:
  port: 8083
spring:
  application:
    name: delivery
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true

order:
  service:
    url: http://localhost:8082/api

resilience4j:
  circuitbreaker:
    instances:
      order-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50

  retry:
    instances:
      order-service:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      order-service:
        timeoutDuration: 3s