# Configuration du port du serveur
server.port=8081

# Nom de l'application
spring.application.name=menu-service

# Configuration de l'Actuator pour Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Activation des groupes de sondes pour Kubernetes
management.health.probes.enabled=true
management.metrics.web.server.request.autotime.enabled=true