# Server Configuration
spring.application.name=order-service
server.port=8081
server.servlet.context-path=/order

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.achillethomas.order_service=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# URLs des services via DNS Kubernetes
menu.service.url=http://menu-service:8080/menu
delivery.service.url=http://delivery-service:8080/delivery

# Configuration Resilience4j - Circuit Breaker
resilience4j.circuitbreaker.instances.menuService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.menuService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.menuService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.menuService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.deliveryService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.deliveryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.deliveryService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.deliveryService.minimumNumberOfCalls=5

# Configuration Resilience4j - Retry
resilience4j.retry.instances.menuService.maxAttempts=3
resilience4j.retry.instances.menuService.waitDuration=1000
resilience4j.retry.instances.deliveryService.maxAttempts=3
resilience4j.retry.instances.deliveryService.waitDuration=1000

# Configuration Resilience4j - Time Limiter
resilience4j.timelimiter.instances.menuService.timeoutDuration=2s
resilience4j.timelimiter.instances.deliveryService.timeoutDuration=2s
