# URLs for inter-service communication
# Default values for local development. These are overridden by environment variables in Kubernetes.
menu-service.url=http://localhost:8081
delivery-service.url=http://localhost:8083