apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'menu-service'
        static_configs:
          - targets: ['localhost:9000']

      - job_name: 'order-service'
        static_configs:
          - targets: ['localhost:9001']

      - job_name: 'delivery-service'
        static_configs:
          - targets: ['localhost:9002']