apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eatnow-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - menu-service
          - order-service
          - delivery-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "9000"
      interval: 15s
      path: /actuator/prometheus
    - port: "9001"
      interval: 15s
      path: /actuator/prometheus
    - port: "9002"
      interval: 15s
      path: /actuator/prometheus