# Configuration du port du serveur
server.port=8081

# Nom de l'application
spring.application.name=menu-service

# Configuration de l'Actuator pour Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
